Output deps path on successful build

diff --git a/scripts/rock-build-node b/scripts/rock-build-node
--- a/scripts/rock-build-node
+++ b/scripts/rock-build-node
@@ -1,10 +1,11 @@
 #!/usr/bin/env bash
 
 path="${1:$( pwd )}"
-deps_path="${path}/package.json"
+deps_path="${path}/node_modules"
+file_path="${path}/package.json"
 
-if [[ ! -f "$deps_path" ]]; then
-  echo "File not found: ${deps_path}" >&2
+if [[ ! -f "$file_path" ]]; then
+  echo "File not found: ${file_path}" >&2
   exit 1
 fi
 
@@ -15,3 +16,5 @@ fi
 if ! npm install >&2 && npm rebuild >&2; then
   exit 1
 fi
+
+echo -n "$deps_path"
diff --git a/scripts/rock-build-python b/scripts/rock-build-python
--- a/scripts/rock-build-python
+++ b/scripts/rock-build-python
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
 
 path="${1:$( pwd )}"
-deps_path="${path}/requirements.txt"
-virtualenv_path="${path}/vendor/virtualenv"
+deps_path="${path}/vendor/virtualenv"
+file_path="${path}/requirements.txt"
 
-if [[ ! -f "$deps_path" ]]; then
-  echo "File not found: ${deps_path}" >&2
+if [[ ! -f "$file_path" ]]; then
+  echo "File not found: ${file_path}" >&2
   exit 1
 fi
 
@@ -13,12 +13,14 @@ if ! cd "$path"; then
   exit 1
 fi
 
-if [[ ! -f "${virtualenv_path}/bin/activate" ]]; then
-  if ! virtualenv "$virtualenv_path" >&2; then
+if [[ ! -f "${deps_path}/bin/activate" ]]; then
+  if ! virtualenv "$deps_path" >&2; then
     exit 1
   fi
 fi
 
-if ! (. "${virtualenv_path}/bin/activate" && pip install -r "$deps_path") >&2; then
+if ! (. "${deps_path}/bin/activate" && pip install -r "$file_path") >&2; then
   exit 1
 fi
+
+echo -n "$deps_path"
diff --git a/scripts/rock-build-ruby b/scripts/rock-build-ruby
--- a/scripts/rock-build-ruby
+++ b/scripts/rock-build-ruby
@@ -1,10 +1,11 @@
 #!/usr/bin/env bash
 
 path="${1:$( pwd )}"
-deps_path="${path}/Gemfile.lock"
+deps_path="${path}/vendor/virtualenv"
+file_path="${path}/Gemfile.lock"
 
-if [[ ! -f "$deps_path" ]]; then
-  echo "File not found: ${deps_path}" >&2
+if [[ ! -f "$file_path" ]]; then
+  echo "File not found: ${file_path}" >&2
   exit 1
 fi
 
@@ -15,3 +16,5 @@ fi
 if ! bundle install --deployment >&2; then
   exit 1
 fi
+
+echo -n "$deps_path"
