Convert perl to carton and remove dest option

diff --git a/scripts/rock-build-node b/scripts/rock-build-node
--- a/scripts/rock-build-node
+++ b/scripts/rock-build-node
@@ -1,26 +1,15 @@
 #!/usr/bin/env bash
 
-src_path="$1"
-dst_path="$2"
+path="${1:$( pwd )}"
+deps_path="${path}/package.json"
 
-if [[ ! -f "${src_path}/package.json" ]]; then
-  echo 'Node projects must contain a "package.json" file' >&2
+if [[ ! -f "$deps_path" ]]; then
+  echo "File not found: ${deps_path}" >&2
   exit 1
 fi
 
-rock-build-setup "$src_path" "$dst_path"
-
-if [[ -e "${src_path}/node_modules" && ! -L "${src_path}/node_modules" ]]; then
-  echo "node_modules exists and isn't a symbolic link" >&2
+if ! cd "$path"; then
   exit 1
-fi
-
-if ! mkdir -p "${dst_path}/node_modules" >&2; then
-  exit 1
-fi
-
-if [[ ! -L "${src_path}/node_modules" ]]; then
-  ln -s "${dst_path}/node_modules" "${src_path}/node_modules"
 fi
 
 if ! npm install >&2 && npm rebuild >&2; then
diff --git a/scripts/rock-build-perl b/scripts/rock-build-perl
--- a/scripts/rock-build-perl
+++ b/scripts/rock-build-perl
@@ -1,15 +1,17 @@
 #!/usr/bin/env bash
 
-src_path="$1"
-dst_path="$2"
+path="${1:$( pwd )}"
+deps_path="${path}/carton.lock"
 
-if [[ ! -f "${src_path}/Makefile.PL" ]]; then
-  echo 'Perl projects must contain a "Makefile.PL" file' >&2
+if [[ ! -f "$deps_path" ]]; then
+  echo "File not found: $deps_path" >&2
   exit 1
 fi
 
-rock-build-setup "$src_path" "$dst_path"
+if ! cd "$path"; then
+  exit 1
+fi
 
-if ! cpanm --local-lib "$dst_path" --skip-satisfied --installdeps "$src_path" >&2; then
+if ! carton --deployment >&2; then
   exit 1
 fi
diff --git a/scripts/rock-build-python b/scripts/rock-build-python
--- a/scripts/rock-build-python
+++ b/scripts/rock-build-python
@@ -1,21 +1,24 @@
 #!/usr/bin/env bash
 
-src_path="$1"
-dst_path="$2"
+path="${1:$( pwd )}"
+deps_path="${path}/requirements.txt"
+virtualenv_path="${path}/vendor/virtualenv"
 
-if [[ ! -f "$src_path/requirements.txt" ]]; then
-  echo 'Python projects must contain a "requirements.txt" file' >&2
+if [[ ! -f "$deps_path" ]]; then
+  echo "File not found: ${deps_path}" >&2
   exit 1
 fi
 
-rock-build-setup "$src_path" "$dst_path"
+if ! cd "$path"; then
+  exit 1
+fi
 
-if [[ ! -f "${dst_path}/bin/activate" ]]; then
-  if ! virtualenv "$dst_path" >&2; then
+if [[ ! -f "${virtualenv_path}/bin/activate" ]]; then
+  if ! virtualenv "$virtualenv_path" >&2; then
     exit 1
   fi
 fi
 
-if ! (. "${dst_path}/bin/activate" && pip install -r "${src_path}/requirements.txt") >&2; then
+if ! (. "${virtualenv_path}/bin/activate" && pip install -r "$deps_path") >&2; then
   exit 1
 fi
diff --git a/scripts/rock-build-ruby b/scripts/rock-build-ruby
--- a/scripts/rock-build-ruby
+++ b/scripts/rock-build-ruby
@@ -1,15 +1,17 @@
 #!/usr/bin/env bash
 
-src_path="$1"
-dst_path="$2"
+path="${1:$( pwd )}"
+deps_path="${path}/Gemfile.lock"
 
-if [[ ! -f "$src_path/Gemfile.lock" ]]; then
-  echo 'Ruby projects must contain a "Gemfile.lock" file' >&2
+if [[ ! -f "$deps_path" ]]; then
+  echo "File not found: ${deps_path}" >&2
   exit 1
 fi
 
-rock-build-setup "$src_path" "$dst_path"
+if ! cd "$path"; then
+  exit 1
+fi
 
-if ! bundle install --deployment --path "$dst_path" >&2; then
+if ! bundle install --deployment >&2; then
   exit 1
 fi
